version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - "api"
    environment:
      - API_HOST=api:3000
  db:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: 
      context: git@github.com:DockerCon2017/api.git
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
