version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: 
      context: git@github.com:DockerCon2017/api.git
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
